Get Involved Page
redbadger/esma-website pull request #82
Opened 2020-09-04 13:24 UTC by sjltaylor

- [ ] navigation comes from the content query?

2020-09-07 14:46 UTC, rjkerrison requested changes
wearing a critical semantic HTML hat 👷‍♀️

2020-09-07 14:46 UTC, rjkerrison commented on src/pages/get-involved.js
> +import linkedInImage from "../images/LinkedIn-Logos/LI-In-Bug.png";
Can these paths be lowercase only? I don't want to deal with case-sensitive filepath-clash bugs, and it just looks weird.

2020-09-07 14:46 UTC, rjkerrison commented on src/pages/get-involved.js
> +    max-width: 1024px;
Use `rem` with the basis `1rem == 16px`. There are [plugins to convert them for Visual Studio](https://marketplace.visualstudio.com/items?itemName=sainoba.px-to-rem).

2020-09-07 14:46 UTC, rjkerrison commented on src/pages/get-involved.js
> +    width: 445px;
When converting this to `rem` I'd round down to a neater `27.5rem`.

2020-09-07 14:46 UTC, rjkerrison commented on src/pages/get-involved.js
> +    margin: 0 95px;
`0 6rem`

2020-09-07 14:46 UTC, rjkerrison commented on src/pages/get-involved.js
> +    <HeroBackgroundImage className="header">
cool, this is going to clash with @tkeburia's change in #83 which renamed it to `FilteredBackgroundImage`, so if this PR lives longer we should correct it before merging

2020-09-07 14:46 UTC, rjkerrison commented on src/pages/get-involved.js
> +      <h1>Ways to get involved</h1>
If this is `h1` and the ESMA name in the page header is still an `h1`, then we have two on the page, which is bad practice for SEO, screenreading, and semantic reasons.

2020-09-07 14:46 UTC, rjkerrison commented on src/pages/get-involved.js
> +          <div className="image-placeholder" style={{backgroundColor: "pink", borderRadius: "9999px", width: "60px", height: "60px", float: "left", margin: "2.25em" }}></div>
Can this styling be set against a class in the `mainCss`?

2020-09-07 14:46 UTC, rjkerrison commented on src/pages/get-involved.js
> +          <h2>Barry Matthews <a className="linked-in" href="https://www.linkedin.com/in/barry-matthews-0970704/"><img alt="linked-in" src={linkedInImage} /></a></h2>
I don't think this should be a heading, but maybe it would be if there's more of a bio here.

2020-09-07 14:46 UTC, rjkerrison commented on src/pages/get-involved.js
> +    <div className="contact-items">
Since this is a list, I'd be inclined to go for `ul.contact-items` and `li.contact-item`.

2020-09-07 14:46 UTC, rjkerrison commented on src/pages/get-involved.js
> +      <SEO title="Home" />
`title` needs to be updated to include `"Get Involved"`

2020-09-08 10:08 UTC, rjkerrison approved these changes

2020-09-08 10:13 UTC, tkeburia approved these changes

2020-09-08 11:53 UTC, merged